# check the file name
name: perf_test_1-15
dataset: data/unsw_nb15.csv
desc: Constraint performance test with 12 constraints

validate: true
cls: xgb
attack: hsj
hsj:
  max_iter: 5

dnn:
  layers: [ 64, 64, 32 ]

cpgd:
  feat_file: "data/feature_unsw.csv"

constraints:
  predicates:
     #  add 3 more Feature-correlated constraints
    - state_INT != 1 or (sbytes > 0 and dbytes == 0)     # checked = T
    - service_dns != 1  or smean <= 512                  # checked = T
    - dbytes != 0 or dloss == 0                          # checked = T


