# check the file name
name: perf_test_1-14
dataset: data/unsw_nb15.csv
desc: Constraint performance test with 12 constraints

dnn:
  layers: [ 64, 64, 32 ]

cpgd:
  feat_file: "data/feature_unsw.csv"

constraints:
  predicates:
    #  add 12 more Feature-value constraints
    # If window size is represented as 8 bits field, then swin and dwin should be in this range: [0,255]
    - swin >= 0 or swin <= 255
    - dwin >= 0 or dwin <= 255
    - sloss >= 0 or sloss <= 3993
    - dloss >= 0 or dloss <= 2627
    - sbytes >= 0 or sbytes <= 7085342
    - dbytes >= 46 or dbytes <= 10508068
    - dur >= 0 or dur <= 60
    - ct_srv_src >= 1 or ct_srv_src <= 63
    - ct_dst_ltm >= 1 or ct_dst_ltm <= 50
    - ct_src_dport_ltm >= 1 or ct_src_dport_ltm <= 50
    - ct_dst_sport_ltm >= 1 or ct_dst_sport_ltm <= 46
    - ct_dst_src_ltm >= 1 or ct_dst_src_ltm <= 63
