name: UNSW2-NB15
dataset: data/unsw_nb15.csv
desc: sampled from 175K training set, immutable categorical attrs.

dnn:
  layers: [ 64, 64, 32 ]

cpgd:
  feat_file: "data/feature_unsw.csv"

constraints:
  immutable:
    - proto_tcp
    - proto_udp
    - proto_other
    - service_none
    - service_http
    - service_dns
    - service_other
    - state_FIN
    - state_INT
    - state_other
