# check the file name
name: perf_test_1-14
dataset: data/unsw_nb15.csv
desc: Constraint performance test with 12 constraints

dnn:
  layers: [ 64, 64, 32 ]

cpgd:
  feat_file: "data/feature_unsw.csv"

constraints:
  predicates:
    #  add 12 more Feature-value constraints
    # If window size is represented as 8 bits field, then swin and dwin should be in this range: [0,255]
    # there is some anomaly value  for swin (176), I fixed it.
    - swin == 0 or swin == 255
    - dwin == 0 or dwin == 255
    - sloss >= 0 and sloss <= 3993
    - dloss >= 0 and dloss <= 2627
    - sbytes >= 0 and sbytes <= 15285342
    - dbytes >= 0 and dbytes <= 19508068
    - dur >= 0 and dur <= 60
    - ct_srv_src >= 1 and ct_srv_src <= 63
    - ct_dst_ltm >= 1 and ct_dst_ltm <= 50
    - ct_src_dport_ltm >= 1 and ct_src_dport_ltm <= 50
    - ct_dst_sport_ltm >= 1 and ct_dst_sport_ltm <= 46
    - ct_dst_src_ltm >= 1 and ct_dst_src_ltm <= 63