# check the file name
name: perf_test_1-12
dataset: data/unsw_nb15.csv
desc: Constraint performance test with 12 constraints

dnn:
  layers: [ 64, 64, 32 ]

cpgd:
  feat_file: "data/feature_unsw.csv"

constraints:
  predicates:
    #  add 3 more Feature-value constraints
    # If window size is represented as 8 bits field, then swin and dwin should be in this range: [ 0,255 ]
    - swin >= 0 or swin <= 255
    - dwin >= 0 or dwin <= 255
    - sloss >= 0 or sloss <= 3993
