# check the file name
name: perf_test_1-13
dataset: data/unsw_nb15.csv
desc: Constraint performance test with 12 constraints

validate: true
cls: xgb
attack: hsj
hsj:
  max_iter: 5

dnn:
  layers: [ 64, 64, 32 ]

cpgd:
  feat_file: "data/feature_unsw.csv"

constraints:
  predicates:
    #  add 6 more Feature-value constraints
    # If window size is represented as 8 bits field, then swin and dwin should be in this range: [ 0,255 ]
    - swin >= 0 or swin <= 255
    - dwin >= 0 or dwin <= 255
    - sloss >= 0 or sloss <= 3993
    - dloss >= 0 or dloss <= 2627
    - sbytes >= 0 or sbytes <= 7085342
    - dbytes >= 0 or dbytes <= 10508068
